DROP DATABASE IF EXISTS MovieCatalogue;

CREATE DATABASE IF NOT EXISTS MovieCatalogue;

USE MovieCatalogue;

CREATE TABLE IF NOT EXISTS Genre (
GenreID INT PRIMARY KEY AUTO_INCREMENT,
GenreName VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS Director(
DirectorID INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
BirthDate DATE
);

CREATE TABLE IF NOT EXISTS Rating(
RatingID INT PRIMARY KEY AUTO_INCREMENT,
RatingName VARCHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS Actor(
ActorID INT PRIMARY KEY AUTO_INCREMENT,
FirstName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
BirthDate DATE
);

CREATE TABLE IF NOT EXISTS Movie(
MovieID INT PRIMARY KEY AUTO_INCREMENT,
Title VARCHAR(128) NOT NULL,
ReleaseDate DATE,
GenreID INT NULL,
DirectorID INT NULL,
RatingID INT NULL,
    CONSTRAINT `fk_MovieGenre` FOREIGN KEY (`GenreID`) REFERENCES `Genre`(`GenreID`) ON DELETE NO ACTION,
    CONSTRAINT `fk_MovieDirector` FOREIGN KEY (`DirectorID`) REFERENCES `Director`(`DirectorID`),
    CONSTRAINT `fk_MovieRating` FOREIGN KEY (`RatingID`) REFERENCES `Rating`(`RatingID`)
);

CREATE TABLE IF NOT EXISTS CastMembers(
CastMemberID INT PRIMARY KEY AUTO_INCREMENT,
`Role` VARCHAR(50) NOT NULL,
CONSTRAINT fk_ActorID FOREIGN KEY (ActorID) REFERENCES Actor(ActorID),
CONSTRAINT fk_MovieID FOREIGN KEY (MovieID) REFERENCES Movie(MovieID)
);